ref: https://github.com/sweenip/jupyter#selecting-a-python-interpreter-for-jupyter-notebooks-in-vs-code

# Setup in wsl bash
```bash
cd sweeni
uv venv
source .venv/bin/activate
uv pip install -r analyze_requirements.txt
```

```bash
# Resolved 37 packages in 21ms
# Installed 37 packages in 86ms
#  + asttokens==3.0.0
#  + comm==0.2.2
#  + debugpy==1.8.14
#  + decorator==5.2.1
#  + et-xmlfile==2.0.0
#  + executing==2.2.0
#  + ipykernel==6.29.5
#  + ipython==9.4.0
#  + ipython-pygments-lexers==1.1.1
#  + jedi==0.19.2
#  + jinja2==3.1.6
#  + jupyter-client==8.6.3
#  + jupyter-core==5.8.1
#  + markupsafe==3.0.2
#  + matplotlib-inline==0.1.7
#  + nest-asyncio==1.6.0
#  + numpy==2.3.1
#  + openpyxl==3.1.5
#  + packaging==25.0
#  + pandas==2.3.1
#  + parso==0.8.4
#  + pexpect==4.9.0
#  + platformdirs==4.3.8
#  + prompt-toolkit==3.0.51
#  + psutil==7.0.0
#  + ptyprocess==0.7.0
#  + pure-eval==0.2.3
#  + pygments==2.19.2
#  + python-dateutil==2.9.0.post0
#  + pytz==2025.2
#  + pyzmq==27.0.0
#  + six==1.17.0
#  + stack-data==0.6.3
#  + tornado==6.5.1
#  + traitlets==5.14.3
#  + tzdata==2025.2
#  + wcwidth==0.2.13
```

# Select interpreter

https://github.com/sweenip/jupyter#selecting-a-python-interpreter-for-jupyter-notebooks-in-vs-code

In [ ]:
# Test
!pip show numpy

In [ ]:
import pandas as pd
import numpy as np
import pickle

In [ ]:
# `file` was created on WINDOWS using https://github.com/sweenip/OneDriveExplorer/blob/dev/sweeni/ztsdaf1471.md
folder = '/home/sweeni/code/OneDriveExplorer/sweeni/data'
file="SQLite_DB_OneDrive.csv"

In [ ]:
columns=["Type","scopeID","siteID","webID","listID","tenantID","webURL","remotePath","spoPermissions","shortcutVolumeID","shortcutItemIndex","libraryType","parentResourceID","resourceID","eTag","Name","fileStatus","lastKnownPinState","volumeID","itemIndex","diskLastAccessTime","diskCreationTime","lastChange","size","localHashDigest","localHashAlgorithm","sharedItem","firstHydrationTime","lastHydrationTime","hydrationCount","lastHydrationType","Media","parentScopeID","folderStatus","folderColor","MountPoint","Path","fileName","graphMetadataJSON","spoCompositeID","createdBy","modifiedBy","filePolicies","fileExtension","lastWriteCount"]

required_fields = ['Type', "parentResourceID","resourceID", "Name", 'fileStatus', "volumeID", "itemIndex", 'diskCreationTime', 'lastChange', 'size', "parentScopeID",'folderStatus', 'Path', 'fileName', 'lastWriteCount']

In [59]:
df = pd.read_csv(folder + "/" + file, skipinitialspace=True, usecols=required_fields,
                 converters={'diskCreationTime': pd.to_datetime,
                             'lastChange': pd.to_datetime,
                            "size": lambda x: x.replace(" KB", "").replace(",", ""),
                             }, 
                 dtype={'Type' : 'category',
                        'fileStatus' : 'category',
                        'folderStatus' : 'category',
                        "volumeID" : 'category',
                        "parentScopeID" : 'category',
                        "lastWriteCount" : pd.Int64Dtype,
                        # used  Nullable Integer Dtypes instaed of np.int64 to avoid error 
                        # "ValueError: Integer column has NA values in column NN"
                        }
                )

/tmp/ipykernel_13770/801013483.py:1: UserWarning: Instantiating Int64Dtype without any arguments.Pass a Int64Dtype instance to silence this warning.
  df = pd.read_csv(folder + "/" + file, skipinitialspace=True, usecols=required_fields,
/tmp/ipykernel_13770/801013483.py:1: UserWarning: Instantiating Int64Dtype without any arguments.Pass a Int64Dtype instance to silence this warning.
  df = pd.read_csv(folder + "/" + file, skipinitialspace=True, usecols=required_fields,

In [ ]:
df['size'] = pd.to_numeric(df['size'], errors='coerce')  # Convert size to Int64 dtype
#Reorder

ordered_fields = ['Path', 'fileName', "Name", 'Type', 'size', 'lastChange',  'diskCreationTime', 'lastWriteCount',"parentResourceID","resourceID", 'fileStatus', 'folderStatus', "volumeID", "itemIndex", "parentScopeID"]
df = df[ordered_fields]
# df.head()

,Path,fileName,Name,Type,size,lastChange,diskCreationTime,lastWriteCount,parentResourceID,resourceID,fileStatus,folderStatus,volumeID,itemIndex,parentScopeID
0,df9e9e556244467b9dabdc62d965839f\\ztsdaf1471\F...,DP_WLAN_wnt5_x86-32_1003.7z,DP_WLAN_wnt5_x86-32_1003.7z,File,22921.0,2010-03-26 03:25:31,2025-07-09 17:35:05,15876,66ba28d759df202280f533f402000000,66ba28d759df202280f5a90c03000000,2,NaN,795181316,2.814750e+14,NaN
1,df9e9e556244467b9dabdc62d965839f\\ztsdaf1471\F...,DP_MassStorage_wnt5_x86-32_901.7z,DP_MassStorage_wnt5_x86-32_901.7z,File,5722.0,2010-03-26 03:25:57,2025-07-09 15:55:08,1022,66ba28d759df202280f531f402000000,66ba28d759df202280f5a70c03000000,2,NaN,795181316,2.814750e+14,NaN
2,df9e9e556244467b9dabdc62d965839f\\ztsdaf1471\F...,DP_LAN_wnt5_x86-32_1003.7z,DP_LAN_wnt5_x86-32_1003.7z,File,8142.0,2010-03-26 03:24:43,2025-07-09 17:35:04,15877,66ba28d759df202280f52ff402000000,66ba28d759df202280f5a60c03000000,2,NaN,795181316,2.814750e+14,NaN
3,df9e9e556244467b9dabdc62d965839f\\ztsdaf1471\F...,MovieTem.dat,MovieTem.dat,File,34.0,2002-04-12 10:50:28,2025-07-09 15:55:06,1044,66ba28d759df202280f5fff302000000,66ba28d759df202280f5600c03000000,2,NaN,795181316,2.814750e+14,NaN
4,df9e9e556244467b9dabdc62d965839f\\ztsdaf1471\F...,PreTempl.dat,PreTempl.dat,File,22.0,2002-04-12 10:39:42,2025-07-09 17:35:25,15737,66ba28d759df202280f5fff302000000,66ba28d759df202280f55f0c03000000,2,NaN,795181316,2.814750e+14,NaN

In [61]:
with open(folder + "/" + 'out.pickle','wb') as f:
    pickle.dump(df,f)

In [62]:
with open(folder + "/" + 'out.pickle','rb') as f:
    df=pickle.load(f)

In [56]:
df['parentScopeID'].unique()  # Check unique values in parentScopeID
# df9e9e556244467b9dabdc62d965839f may be sweeni@hotmail.com

[NaN, 'df9e9e556244467b9dabdc62d965839f']
Categories (1, object): ['df9e9e556244467b9dabdc62d965839f']

In [ ]:
# df[(df['fileName']!=df['Name'])&(df['Type']!="Folder")].head()

,Path,fileName,Name,Type,size,lastChange,diskCreationTime,lastWriteCount,parentResourceID,resourceID,fileStatus,folderStatus,volumeID,itemIndex,parentScopeID
21388,df9e9e556244467b9dabdc62d965839f\\Documents,NaN,Personal (Web).url,File,1.0,2014-08-01 01:12:07,NaT,<NA>,66ba28d759df202280f5270100000000,66ba28d759df202280f5950100000000,2,NaN,1847712329,1.351080e+16,NaN
21408,NaN,NaN,NaN,Scope,NaN,NaT,NaT,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# df[df['Type']=="Scope"].head()

In [63]:
# Remove the Scope record
df=df[df['Type']!="Scope"]

# Remove prefix
df['Path']=df['Path'].str.replace("df9e9e556244467b9dabdc62d965839f", "")
#df.head()